CREATE TABLE IF NOT EXISTS user (
    id BIGINT  PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255)  NOT NULL
);

CREATE TABLE IF NOT EXISTS link (
    id BIGINT  PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    url VARCHAR(255)  NOT NULL,
    icon_url VARCHAR(255)  NOT NULL,
    user_id BIGINT  NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);